Repository ISPP-Grupo-7/MapYourWorld, pull requests merged in 2025-03, with the labels that each got.

#74 Feature/backend auth service
  .gitignore
  backend/auth-service/babel.config.ts
  backend/auth-service/jest.config.ts
  backend/auth-service/src/index.ts
  backend/auth-service/src/models/blacklisted_token.model.ts
  backend/auth-service/src/models/user.model.ts
  backend/auth-service/src/routes/auth.routes.ts
  backend/auth-service/src/routes/email.routes.ts
  backend/auth-service/src/services/admin.service.ts
  backend/auth-service/src/services/auth.service.ts
  backend/auth-service/src/tests/email.mock.ts
  backend/auth-service/src/tests/jwt.mock.test.ts
  backend/database/appDataSource.ts
  backend/database/db.ts
  backend/index.ts
  backend/map-service/src/controllers/poi.controller.ts
  backend/map-service/src/models/poi.model.ts
  backend/map-service/src/routes/poi.routes.ts
  backend/map-service/src/services/district.service.ts
  backend/map-service/src/services/poi.service.ts
  backend/map-service/src/tests/poi.mock.test.ts
  backend/types/common/common.types.ts
  backend/types/user/user.model.types.ts
  frontend/mobile/package.json
  frontend/web/package.json
  package-lock.json
  shared/security/jwt.ts
Labels: enhancement

#77 Actualización de gestión de dependencias y mejoras en configuración del proyecto
  .expoignore
  .gitignore
  .npmrc
  README.md
  actualizar-dependencias.js
  assets/favicon.png
  backend/api-gateway/package.json
  backend/api-gateway/src/middleware/circuit-breaker.ts
  backend/auth-service/package-lock.json
  backend/auth-service/package.json
  backend/map-service/package.json
  backend/notification-service/package.json
  backend/package.json
  backend/social-service/package.json
  backend/tsconfig.json
  backend/user-service/package.json
  frontend/mobile/.babelrc
  frontend/mobile/.npmrc
  frontend/mobile/App.tsx
  frontend/mobile/app.config.js
  frontend/mobile/assets/adaptive-icon.png
  frontend/mobile/assets/favicon.png
  frontend/mobile/assets/icon.png
  frontend/mobile/assets/splash.png
  frontend/mobile/babel.config.js
  frontend/mobile/index.html
  frontend/mobile/metro.config.js
  frontend/mobile/package.json
  frontend/mobile/src/components/Map/MapScreen.web.tsx
  frontend/mobile/src/components/screens/LoginScreen.tsx
  frontend/mobile/src/components/screens/RegisterScreen.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.tsx
  frontend/mobile/src/types/index.d.ts
  frontend/mobile/tailwind.config.js
  frontend/mobile/tsconfig.json
  frontend/mobile/webpack.config.js
  frontend/package.json
  frontend/web/package.json
  package.json
  scripts/limpiar-instalar.js
  scripts/start-minimal.js
  scripts/verificar-entorno.js
  shared/package.json
  shared/websocket/event-handlers.ts
Labels: documentation, enhancement, dependencies

#78 Hotfix: Arreglo de configuración y modulo para expo
  frontend/mobile/App.tsx
  frontend/mobile/app.config.js
  frontend/mobile/metro.config.js
Labels: bug

#140 Mejoras en UI/UX: Iconos personalizados para POIs, optimización de pantallas de bienvenida y registro
  frontend/mobile/src/assets/styles/styles.tsx
  frontend/mobile/src/components/Map/MapScreen.tsx
  frontend/mobile/src/components/Map/MapScreen.web.tsx
  frontend/mobile/src/components/POI/PoiForm.tsx
  frontend/mobile/src/components/screens/RegisterScreen.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.web.tsx
Labels: bug, enhancement

#165 Test/backend auth service
  backend/auth-service/src/tests/auth.test.ts
  backend/auth-service/src/tests/email.mock.test.ts
  backend/auth-service/src/tests/email.mock.ts
  backend/jest.config.js
  frontend/mobile/package.json
Labels: unit test

#177 Feature/backend mvc de pago
  backend/backend_endpoint.ts
  backend/database/appDataSource.ts
  backend/payment-service/controllers/payment.controller.ts
  backend/payment-service/index.ts
  backend/payment-service/routes/payment.routes.ts
  backend/payment-service/src/controllers/payment.controller.ts
  backend/payment-service/src/index.ts
  backend/payment-service/src/models/payment.model.ts
  backend/payment-service/src/repositories/payment.repository.ts
  backend/payment-service/src/routes/payment.routes.ts
  backend/payment-service/src/services/payment.service.ts
  backend/payment-service/test/postman/Payment service.postman_collection.json
Labels: enhancement

#182 Create SECURITY.md
  SECURITY.md
Labels: documentation, security

#183 Corrección de relaciones en UserDistrict y mejora del sistema de coloreado de distritos en mapas colaborativos
  backend/auth-service/src/models/user.model.ts
  backend/backend_endpoint.ts
  backend/database/appDataSource.ts
  backend/map-service/src/controllers/district.controller.ts
  backend/map-service/src/controllers/map.controller.ts
  backend/map-service/src/models/district.model.ts
  backend/map-service/src/models/user-district.model.ts
  backend/map-service/src/repositories/user-district.repository.ts
  backend/map-service/src/routes/district.routes.ts
  backend/map-service/src/services/district.service.ts
  backend/map-service/src/services/map.service.ts
  backend/user-service/src/controllers/user.controller.ts
  backend/user-service/src/repositories/user.repository.ts
  backend/user-service/src/routes/user.routes.ts
  backend/user-service/src/services/user.service.ts
  backend/user-service/src/tests/user.mocks.ts
Labels: bug, enhancement, dependencies

#184 Mejora de cobertura de tests con implementación de mocks para Components y Screens
  frontend/mobile/jest.config.js
  frontend/mobile/jest.setup.js
  frontend/mobile/package.json
  frontend/mobile/src/services/collaborativeMap.service.ts
  frontend/mobile/src/services/poi.service.ts
  frontend/mobile/src/test/README.md
  frontend/mobile/src/test/README_TESTS_NATIVEWIND.md
  frontend/mobile/src/test/__mocks__/fileMock.js
  frontend/mobile/src/test/__mocks__/react-leaflet.js
  frontend/mobile/src/test/__mocks__/react-native-geolocation-service.js
  frontend/mobile/src/test/__mocks__/styleMock.js
  frontend/mobile/src/test/components/Map/CollaborativeMapListScreen.test.tsx
  frontend/mobile/src/test/components/Map/CollaborativeMapScreen.test.tsx
  frontend/mobile/src/test/components/Map/CollaborativeMapScreen.web.test.tsx
  frontend/mobile/src/test/components/Map/MapScreen.test.tsx
  frontend/mobile/src/test/components/Map/MapScreen.web.test.tsx
  frontend/mobile/src/test/components/POI/POICard.test.tsx
  frontend/mobile/src/test/components/UI/Button.test.tsx
  frontend/mobile/src/test/components/UI/Card.test.tsx
  frontend/mobile/src/test/components/UI/HamburgerMenu.test.tsx
  frontend/mobile/src/test/components/UI/SimpleButton.test.tsx
  frontend/mobile/src/test/components/UI/TextInput.test.tsx
  frontend/mobile/src/test/components/screens/ForgotPasswordScreen.test.tsx
  frontend/mobile/src/test/components/screens/LoginScreen.test.tsx
  frontend/mobile/src/test/components/screens/RegisterScreen.test.tsx
  frontend/mobile/src/test/components/screens/WelcomeScreen.test.tsx
  frontend/mobile/src/test/contexts/AuthContext.test.tsx
  frontend/mobile/src/test/jest.d.ts
Labels: enhancement, unit test, ui test, web, mobile

#201 Test/backend user service
  actualizar-dependencias.js
  backend/auth-service/src/index.ts
  backend/auth-service/src/repositories/auth.repository.ts
  backend/auth-service/src/services/auth.service.ts
  backend/auth-service/src/tests/auth.integration.test.ts
  backend/auth-service/src/tests/auth.unit.test.ts
  backend/package.json
  backend/user-service/src/tests/profile.unit.test.ts
  frontend/mobile/package.json
  package.json
  shared/package.json
Labels: enhancement, unit test, dependencies

#200 feat: implementar repository, service, controller, route y tests de userStat
  backend/stat-service/controllers/userStat.controller.ts
  backend/stat-service/models/userStat.model.ts
  backend/stat-service/repositories/userStat.repository.ts
  backend/stat-service/routes/userStat.routes.ts
  backend/stat-service/services/userStat.service.ts
  backend/stat-service/tests/userStat.test.ts
Labels: enhancement, unit test

#211 Implementación de MapScreen.web.tsx y correcion de errores críticos.
  frontend/mobile/src/components/Map/MapScreen.web.tsx
Labels: bug, dependencies, critical

#212 Workflow para correr tests y para crear una PR cada día
  .github/workflows/daily_pr.yaml
  .github/workflows/test.yaml
Labels: dependencies

#215 Feature/frontend achievements
  backend/achievement-service/controllers/achievement.controller.ts
  backend/achievement-service/repositories/achievement.repository.ts
  backend/achievement-service/repositories/userAchievement.repository.ts
  backend/achievement-service/routes/achievement.routes.ts
  backend/achievement-service/services/achievement.service.ts
  backend/backend_endpoint.ts
  frontend/mobile/App.tsx
  frontend/mobile/src/components/Achievements/UserAchievementsScreen.tsx
  frontend/mobile/src/components/Achievements/UserAchievementsScreen.web.tsx
  frontend/mobile/src/components/UI/HamburgerMenu.tsx
Labels: enhancement

#219 Feature/backend designar colores mapas colaborativos
  backend/map-service/src/models/user-district.model.ts
  backend/map-service/src/repositories/district.repository.ts
  backend/map-service/src/repositories/user-district.repository.ts
  backend/map-service/src/services/district.service.ts
  backend/payment-service/tests/subscription.test.ts
Labels: bug, enhancement

#226 fix: Cambiar rutas achievements
  backend/achievement-service/controllers/achievement.controller.ts
  backend/achievement-service/routes/achievement.routes.ts
  backend/achievement-service/routes/userAchievement.routes.ts
  frontend/mobile/src/components/Achievements/UserAchievementsScreen.tsx
Labels: bug

#228 Test/backend auth service
  .github/workflows/test.yaml
  backend/auth-service/src/controllers/auth.controller.ts
  backend/auth-service/src/routes/auth.routes.ts
  backend/auth-service/src/services/auth.service.ts
  backend/auth-service/src/services/token.service.ts
  backend/auth-service/src/tests/auth.integration.test.ts
  backend/auth-service/src/tests/auth.unit.test.ts
  frontend/mobile/package.json
  frontend/mobile/src/test/contexts/AuthContext.test.tsx
Labels: integration test

#233 Feature/collab map inivitations to develop
  backend/achievement-service/controllers/userAchievement.controller.ts
  backend/auth-service/src/controllers/collab.map.controller.ts
  backend/auth-service/src/models/user.model.ts
  backend/auth-service/src/routes/collab.map.routes.ts
  backend/auth-service/src/services/auth.service.ts
  backend/backend_endpoint.ts
  backend/database/map.geojson
  backend/map-service/src/controllers/map.controller.ts
  backend/map-service/src/mocks/district_create.ts
  backend/map-service/src/repositories/map.repository.ts
  backend/map-service/src/routes/map.routes.ts
  backend/map-service/src/services/district.service.ts
  backend/package.json
  backend/payment-service/controllers/stripe.controller.ts
  backend/payment-service/models/subscription.model.ts
  backend/payment-service/repositories/subscription.repository.ts
  backend/payment-service/routes/stripe.routes.ts
  backend/payment-service/services/subscription.service.ts
  backend/social-service/src/controllers/friend.controller.ts
  backend/social-service/src/models/friend.model.ts
  backend/social-service/src/repositories/friend.repository.ts
  backend/social-service/src/routes/friend.routes.ts
  backend/social-service/src/services/friend.service.ts
  frontend/mobile/App.tsx
  frontend/mobile/package.json
  frontend/mobile/src/assets/styles/pricingStyle.ts
  frontend/mobile/src/components/Map/CollaborativeMapScreen.tsx
  frontend/mobile/src/components/UI/HamburgerMenu.tsx
  frontend/mobile/src/components/UI/PricingTable.tsx
  frontend/mobile/src/components/screens/SocialScreen.tsx
  frontend/mobile/src/components/screens/SubscriptionScreen.tsx
  frontend/mobile/src/components/screens/SubscriptionScreen.web.tsx
  frontend/mobile/src/navigation/types.ts
Labels: enhancement, critical

#234 Backend/connect email to register
  backend/auth-service/src/config/email.config.ts
  backend/auth-service/src/services/auth.service.ts
  backend/auth-service/src/services/email.service.ts
  backend/backend_endpoint.ts
Labels: bug, enhancement, dependencies

#235 Feature/frontend formulario publicitario
  frontend/mobile/App.tsx
  frontend/mobile/src/components/screens/AdvertismentForm.tsx
  frontend/mobile/src/components/screens/AdvertismentForm.web.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.web.tsx
  frontend/mobile/src/navigation/types.ts
  frontend/mobile/src/test/components/screens/AdvertisementForm.test.tsx
Labels: enhancement, unit test, ui test

#236 Correciones de bugs en distritos desbloqueados y optimizaciones
  .gitignore
  backend/map-service/src/controllers/district.controller.ts
  frontend/mobile/src/components/Map/CollaborativeMapScreen.web.tsx
  frontend/mobile/src/components/Map/MapScreen.tsx
  frontend/mobile/src/components/Map/MapScreen.web.tsx
  frontend/mobile/src/components/screens/LoginScreen.tsx
  frontend/mobile/src/components/screens/LoginScreen.web.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.web.tsx
Labels: bug, enhancement, security

#209 Feature/backend mvc de foto
  backend/backend_endpoint.ts
  backend/database/appDataSource.ts
  backend/map-service/src/repositories/poi.repostory.ts
  backend/social-service/src/controllers/photo.controller.ts
  backend/social-service/src/models/photo.model.ts
  backend/social-service/src/repositories/photo.repository.ts
  backend/social-service/src/routes/photo.routes.ts
  backend/social-service/src/services/photo.service.ts
  backend/social-service/src/tests/photo.test.ts
Labels: enhancement, unit test

#237 Test/backend social integration
  .github/workflows/test.yaml
  .gitignore
  backend/achievement-service/controllers/achievement.controller.ts
  backend/achievement-service/routes/achievement.routes.ts
  backend/achievement-service/routes/userAchievement.routes.ts
  backend/auth-service/src/config/email.config.ts
  backend/auth-service/src/controllers/auth.controller.ts
  backend/auth-service/src/routes/auth.routes.ts
  backend/auth-service/src/services/auth.service.ts
  backend/auth-service/src/services/email.service.ts
  backend/auth-service/src/services/token.service.ts
  backend/auth-service/src/tests/auth.integration.test.ts
  backend/auth-service/src/tests/auth.unit.test.ts
  backend/backend_endpoint.ts
  backend/database/appDataSource.ts
  backend/index.ts
  backend/map-service/src/controllers/district.controller.ts
  backend/map-service/src/repositories/poi.repostory.ts
  backend/payment-service/controllers/stripe.controller.ts
  backend/payment-service/controllers/subscription.controller.ts
  backend/payment-service/routes/subscription.routes.ts
  backend/social-service/src/controllers/photo.controller.ts
  backend/social-service/src/models/photo.model.ts
  backend/social-service/src/repositories/friend.repository.ts
  backend/social-service/src/repositories/photo.repository.ts
  backend/social-service/src/routes/photo.routes.ts
  backend/social-service/src/services/friend.service.ts
  backend/social-service/src/services/photo.service.ts
  backend/social-service/src/tests/friend.unit.test.ts
  backend/social-service/src/tests/photo.unit.test.ts
  frontend/mobile/App.tsx
  frontend/mobile/package.json
  frontend/mobile/src/assets/styles/pricingStyle.ts
  frontend/mobile/src/components/Achievements/UserAchievementsScreen.tsx
  frontend/mobile/src/components/Map/CollaborativeMapScreen.web.tsx
  frontend/mobile/src/components/Map/MapScreen.tsx
  frontend/mobile/src/components/Map/MapScreen.web.tsx
  frontend/mobile/src/components/screens/AdvertismentForm.tsx
  frontend/mobile/src/components/screens/AdvertismentForm.web.tsx
  frontend/mobile/src/components/screens/LoginScreen.tsx
  frontend/mobile/src/components/screens/LoginScreen.web.tsx
  frontend/mobile/src/components/screens/SubscriptionScreen.tsx
  frontend/mobile/src/components/screens/SubscriptionScreen.web.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.tsx
  frontend/mobile/src/components/screens/WelcomeScreen.web.tsx
  frontend/mobile/src/navigation/types.ts
  frontend/mobile/src/test/components/screens/AdvertisementForm.test.tsx
  frontend/mobile/src/test/contexts/AuthContext.test.tsx
  hello.txt
Labels: unit test

#243 Feature/frontend logros web
  frontend/mobile/src/components/Achievements/UserAchievementsScreen.tsx
  frontend/mobile/src/components/Achievements/UserAchievementsScreen.web.tsx
  frontend/mobile/src/components/UI/Alert.tsx
Labels: enhancement, web, mobile
